version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "7227"
      MYSQL_DATABASE: "simplenotesdb"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  simple-notes-api:
    build: .
    depends_on:
        mysql:
            condition: service_healthy
    environment:
      # Connection string to point to 'mysql' service in docker network
      ConnectionStrings__Default: "Server=mysql;Port=3306;Database=simplenotesdb;User=root;Password=7227;"
    ports:
      - "8080:8080"
    restart: unless-stopped
